# -*- coding: utf-8 -*-
"""capacitor_seno.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IuQmL0uZKn780U9DpFsEYqvc2zEAUn5r
"""

#Capacitor Seno (Exemplo 6.3)

import numpy as np
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# Exemplo 6.3: Cálculo da capacitância para interface dada por
# f(x) = (h/2)[1 + sen(2*pi*x/W)], com unidades físicas (SI)
# e impressão em Farads [F], Eq. (16) do manuscrito
# ------------------------------------------------------------

# ---------------------------------------------------------------
# Parâmetros do usuário
# ---------------------------------------------------------------
# A constante ε0 é a permissividade do vácuo em Farad por metro (F/m)
ε0 = 8.8541878128e-12  # F/m

#----------------------------------------------------------------
# Geometria
#----------------------------------------------------------------

# Parâmetros geométricos em mm (para facilitar a leitura)
W_mm = 50.0      # Largura da placa em mm
L_mm = 50.0      # Profundidade em mm
h_mm = 5.0       # Separação entre as placas em mm

# Conversão dos parâmetros para metros
W = W_mm * 1e-3  # Converte largura da placa de mm para metros
L = L_mm * 1e-3  # Converte profundidade de mm para metros
h = h_mm * 1e-3  # Converte distância entre as placas de mm para metros

# Permissividades relativas dos dielétricos (exemplo: material 1 e material 2)
k1 = 1.0         # ε1_rel (permissividade relativa do primeiro dielétrico)
k2 = 5.0         # ε2_rel (permissividade relativa do segundo dielétrico)

# Conversão para permissividades absolutas
# (multiplicando pelas permissividades do vácuo)
ε1 = k1*ε0     # Permissividade absoluta do primeiro dielétrico
ε2 = k2*ε0     # Permissividade absoluta do segundo dielétrico


# Número de separações para o calculo discreto
N = 10000

# ---------------------------------------------------------------
# Perfil de interface senoidal extrudado
# ---------------------------------------------------------------
def f_sine(x, h, W, n):
    return 0.5*h*(1 + np.sin(2*np.pi*n*x/W))

# ---------------------------------------------------------------
# Capacitância numérica via soma de Riemann pelo ponto médio
# ---------------------------------------------------------------
def C_numeric(ε1, ε2, h, W, L, n, N):
    xs = np.linspace(0, W, N, endpoint=False)
    dx = W/N
    fvals = f_sine(xs + 0.5*dx, h, W, n)
    denom = (ε2 - ε1)*fvals + ε1*h
    integrand = ε1*ε2*L / denom
    return np.sum(integrand)*dx

# Expressão analítica
def C_analytic(ε1, ε2, h, W, L):
    return (W*L/h)*np.sqrt(ε1*ε2)

# ---------------------------------------------------------------
# Compare a capacitância analítica e a numérica para múltiplos
# valores para o número de comprimentos de ondas (períodos) n
# ---------------------------------------------------------------
n_values = [1, 2, 3, 5, 10]

# Exibição dos parâmetros e resultados
print("Parâmetros:")
print(f"  W = {W_mm} mm, L = {L_mm} mm, h = {h_mm} mm")
print(f"  k1 = {k1}, k2 = {k2}")
print(f"  N = {N} fatias\n")

C_ana = C_analytic(ε1, ε2, h, W, L)
print("Capacitância analítica:", C_ana)
print()

for n in n_values:
    C_num = C_numeric(ε1, ε2, h, W, L, n, N)
    rel_err = abs(C_num - C_ana)/abs(C_ana)
    print("n =", n)
    print("  Capacitância numérica:", C_num)
    print("  Erro relativo:", rel_err)
    print()